include("api/common/configurations.jl")
include("api/common/data_alignment.jl")
include("api/common/result_builders.jl")
include("api/common/summary.jl")
include("api/univariate/proposal.jl")
include("api/univariate/detect.jl")
include("api/multivariate/traits.jl")
include("api/multivariate/proposal.jl")
include("api/multivariate/detect.jl")

